# Author: Bucky Frost
# File: Makefile
# Purpose: Makefile for CS 405
# 
CC = g++
CFLAGS = -Wall -g -std=c++11
INCLUDES = -I ./includes/
# LFLAGS
# LIBS
SRCS = ./src/*
all:
	$(CC) $(CFLAGS) $(INCLUDES) $(SRCS)  -o ./build/test.out
